### ISSUE TITLE
fraction.imag is non-zero

### ISSUE THREAD

**Issue by Yogi-B** [scoder/quicktions#1]
Well, except for when `int(fraction) == 0` as that is what the `imag` property actually returns, as of 0636b8223225fdc0ecd89b66c5406643135f66c0 onwards.

**Comment by scoder** [comment]
Interesting, thanks for catching it. I can't believe there's no test for this...

**Comment by scoder** [comment]
https://github.com/scoder/quicktions/commit/3def2248f6c7905d14836c023ceaaac30e60ba44
