### ISSUE TITLE
No name 'Fraction' in module 'quicktions' (no-name-in-module)

### ISSUE THREAD

**Issue by benjaminweb** [scoder/quicktions#3]
When I run ``pylint``, I get this error:

`E:  1, 0: No name 'Fraction' in module 'quicktions' (no-name-in-module)`

Solution: Add ``__init__.py`` to ``src``, see http://stackoverflow.com/a/41184125/2490706.

``src`` served as my place of choice for the main code. I learned later on that this is no good choice for the name (it might confuse some wheels of the system, can't remember which). It is better to name it ``quicktions``.

Simply borrow from:

https://github.com/pallets/click
https://github.com/crsmithdev/arrow/

**Comment by scoder** [comment]
"src" is not a package but a directory. And note that pylint won't help much with Cython code.
